// AUTO-DERIVED from 001_initial.sql + types/supabase.ts.
//
// For each synced user-data table, maps column name -> ColumnKind. Used
// by the sync layer + service layer to coerce values between SQLite's
// TEXT/INTEGER/REAL storage and JS-typed domain objects.
//
// Kinds:
//   'text'      — TEXT passthrough (strings, uuids, timestamps, enums)
//   'integer'   — INTEGER passthrough (counts, numbers)
//   'real'      — REAL passthrough (floats, numerics)
//   'boolean'   — SQLite INTEGER 0/1 <-> JS boolean
//   'json'      — SQLite TEXT JSON string <-> JS object/array
//   'dirty_flag'— SQLite-only sync housekeeping (_dirty, _deleted)
//
// For the purpose of coercion:
//   fromSqlite:
//     boolean -> Boolean(val)
//     json    -> val == null ? null : JSON.parse(val as string)
//     others  -> val
//   toSqlite:
//     boolean -> val ? 1 : 0
//     json    -> val == null ? null : JSON.stringify(val)
//     others  -> val

export type ColumnKind = 'text' | 'integer' | 'real' | 'boolean' | 'json' | 'dirty_flag';

export type TableColumns = Record<string, ColumnKind>;

export const COLUMN_TYPES: Record<string, TableColumns> = {
  achievements_unlocked: {
    id: 'text',
    user_id: 'text',
    achievement_id: 'text',
    unlocked_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  boss_challenges: {
    id: 'text',
    user_id: 'text',
    boss_id: 'text',
    started_at: 'text',
    progress: 'integer',
    days_required: 'integer',
    evaluator_type: 'text',
    day_results: 'json',
    status: 'text',
    resolved_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  budgets: {
    id: 'text',
    user_id: 'text',
    category: 'text',
    monthly_limit: 'real',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  completions: {
    id: 'text',
    user_id: 'text',
    task_id: 'text',
    engine: 'text',
    date_key: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  deep_work_logs: {
    id: 'text',
    user_id: 'text',
    task_id: 'text',
    date_key: 'text',
    completed: 'boolean',
    earnings_today: 'real',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  deep_work_sessions: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    task_name: 'text',
    category: 'text',
    minutes: 'integer',
    started_at: 'text',
    ended_at: 'text',
    notes: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  deep_work_tasks: {
    id: 'text',
    user_id: 'text',
    task_name: 'text',
    category: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  field_op_cooldown: {
    user_id: 'text',
    cooldown_until: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  field_ops: {
    id: 'text',
    user_id: 'text',
    field_op_id: 'text',
    current_day: 'integer',
    day_results: 'json',
    status: 'text',
    started_at: 'text',
    completed_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  focus_sessions: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    duration_minutes: 'integer',
    category: 'text',
    completed: 'boolean',
    started_at: 'text',
    ended_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  focus_settings: {
    user_id: 'text',
    pomodoro_minutes: 'integer',
    break_minutes: 'integer',
    daily_target_sessions: 'integer',
    sound_enabled: 'boolean',
    updated_at: 'text',
    long_break_minutes: 'integer',
    long_break_after: 'integer',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  goals: {
    id: 'text',
    user_id: 'text',
    title: 'text',
    target_date: 'text',
    status: 'text',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  gym_exercises: {
    id: 'text',
    user_id: 'text',
    name: 'text',
    muscle_group: 'text',
    equipment: 'text',
    notes: 'text',
    is_custom: 'boolean',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  gym_personal_records: {
    id: 'text',
    user_id: 'text',
    exercise_name: 'text',
    weight: 'real',
    reps: 'integer',
    achieved_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  gym_sessions: {
    id: 'text',
    user_id: 'text',
    template_id: 'text',
    name: 'text',
    started_at: 'text',
    ended_at: 'text',
    notes: 'text',
    date_key: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  gym_sets: {
    id: 'text',
    user_id: 'text',
    session_id: 'text',
    exercise_id: 'text',
    exercise_name: 'text',
    set_index: 'integer',
    weight: 'real',
    reps: 'integer',
    rpe: 'real',
    notes: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  gym_templates: {
    id: 'text',
    user_id: 'text',
    name: 'text',
    description: 'text',
    exercise_ids: 'json',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  habit_logs: {
    id: 'text',
    user_id: 'text',
    habit_id: 'text',
    date_key: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  habits: {
    id: 'text',
    user_id: 'text',
    title: 'text',
    engine: 'text',
    icon: 'text',
    trigger_text: 'text',
    duration_text: 'text',
    frequency: 'text',
    current_chain: 'integer',
    best_chain: 'integer',
    last_broken_date: 'text',
    created_at: 'text',
    updated_at: 'text',
    legacy_local_id: 'integer',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  journal_entries: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    content: 'text',
    updated_at: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  meal_logs: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    name: 'text',
    calories: 'integer',
    protein_g: 'real',
    carbs_g: 'real',
    fat_g: 'real',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  mind_training_results: {
    id: 'text',
    user_id: 'text',
    exercise_id: 'text',
    type: 'text',
    category: 'text',
    correct: 'boolean',
    selected_option: 'text',
    time_spent_ms: 'integer',
    answered_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  money_loans: {
    id: 'text',
    user_id: 'text',
    lender: 'text',
    name: 'text',
    amount: 'real',
    paid: 'real',
    date_iso: 'text',
    due_iso: 'text',
    status: 'text',
    interest_rate: 'real',
    monthly_payment: 'real',
    start_date: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  money_transactions: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    amount: 'real',
    category: 'text',
    type: 'text',
    note: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  narrative_entries: {
    id: 'text',
    user_id: 'text',
    flag: 'text',
    seen_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  narrative_log: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    type: 'text',
    text: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  nutrition_profile: {
    user_id: 'text',
    sex: 'text',
    age: 'integer',
    height_cm: 'real',
    weight_kg: 'real',
    body_fat_pct: 'real',
    steps_per_day: 'integer',
    workouts_per_week: 'integer',
    goal: 'text',
    goal_rate: 'text',
    protein_preference: 'text',
    daily_calorie_target: 'integer',
    protein_target_g: 'integer',
    carbs_target_g: 'integer',
    fat_target_g: 'integer',
    bmr: 'integer',
    tdee: 'integer',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  profiles: {
    id: 'text',
    email: 'text',
    archetype: 'text',
    mode: 'text',
    focus_engines: 'json',
    xp: 'integer',
    level: 'integer',
    streak_current: 'integer',
    streak_best: 'integer',
    streak_last_date: 'text',
    first_use_date: 'text',
    onboarding_completed: 'boolean',
    tutorial_completed: 'boolean',
    first_task_completed_at: 'text',
    display_name: 'text',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  progression: {
    user_id: 'text',
    current_phase: 'text',
    current_week: 'integer',
    phase_start_week: 'integer',
    first_use_date: 'text',
    phase_start_date: 'text',
    phase_history: 'json',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  protocol_sessions: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    morning_intention: 'text',
    morning_completed_at: 'text',
    evening_reflection: 'text',
    evening_completed_at: 'text',
    titan_score: 'integer',
    identity_at_completion: 'text',
    habit_checks: 'json',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  quests: {
    id: 'text',
    user_id: 'text',
    week_start_key: 'text',
    type: 'text',
    title: 'text',
    description: 'text',
    target: 'integer',
    progress: 'integer',
    status: 'text',
    xp_reward: 'integer',
    metadata: 'json',
    created_at: 'text',
    expires_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  quick_meals: {
    id: 'text',
    user_id: 'text',
    name: 'text',
    calories: 'integer',
    protein_g: 'real',
    carbs_g: 'real',
    fat_g: 'real',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  rank_up_events: {
    id: 'text',
    user_id: 'text',
    from_level: 'integer',
    to_level: 'integer',
    created_at: 'text',
    dismissed_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  skill_tree_progress: {
    id: 'text',
    user_id: 'text',
    engine: 'text',
    node_id: 'text',
    state: 'text',
    progress: 'integer',
    claimed_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  sleep_logs: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    hours_slept: 'real',
    quality: 'integer',
    notes: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  srs_cards: {
    user_id: 'text',
    exercise_id: 'text',
    interval_days: 'integer',
    ease_factor: 'real',
    review_count: 'integer',
    next_review_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  subscriptions: {
    user_id: 'text',
    status: 'text',
    product_id: 'text',
    entitlement_id: 'text',
    period_type: 'text',
    store: 'text',
    original_purchase_date: 'text',
    purchase_date: 'text',
    expires_at: 'text',
    renewed_at: 'text',
    will_renew: 'boolean',
    cancel_reason: 'text',
    last_event_type: 'text',
    last_event_at: 'text',
    raw_event: 'json',
    created_at: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  tasks: {
    id: 'text',
    user_id: 'text',
    engine: 'text',
    title: 'text',
    kind: 'text',
    days_per_week: 'integer',
    is_active: 'boolean',
    created_at: 'text',
    updated_at: 'text',
    legacy_local_id: 'integer',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  titan_mode_state: {
    user_id: 'text',
    unlocked: 'boolean',
    consecutive_days: 'integer',
    average_score: 'real',
    start_date: 'text',
    last_recorded_date: 'text',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  user_titles: {
    user_id: 'text',
    title_id: 'text',
    unlocked_at: 'text',
    equipped: 'boolean',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  water_logs: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    glasses: 'integer',
    updated_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
  weight_logs: {
    id: 'text',
    user_id: 'text',
    date_key: 'text',
    weight_kg: 'real',
    notes: 'text',
    created_at: 'text',
    _dirty: 'dirty_flag',
    _deleted: 'dirty_flag',
  },
};

/** Ordered list of table names that participate in sync (push + pull). */
export const SYNCED_TABLES: readonly string[] = Object.keys(COLUMN_TYPES) as readonly string[];
